services:
  baseline:
    image: whatfpl:baseline
    ports:
      - "8080:8080"

  canary:
    image: whatfpl:canary
    ports:
      - "8081:8080"
    profiles:
      - canary

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
