global:
  scrape_interval: 15s

scrape_configs:
  - job_name: baseline
    static_configs:
      - targets: ['baseline:8080']

  - job_name: canary
    static_configs:
      - targets: ['canary:8080']
